name: OpenTofu Format

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches-ignore:
      - main

permissions:
  contents: write

env:
  TOFU_VERSION: '1.9.0'

jobs:
  opentofu-fmt:
    name: 'OpenTofu Format'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ env.TOFU_VERSION }}

      - name: Run OpenTofu Format
        run: tofu fmt -recursive

      - name: Configure Git to use rebase for pull
        run: git config pull.rebase true

      - name: Add, Commit and Push Fixes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Apply OpenTofu fmt fixes" || echo "No changes to commit"
          git push
