name: OpenTofu CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
  DYNAMODB_TABLE_NAME: ${{ vars.DYNAMODB_TABLE_NAME }}
  KMS_KEY_ALIAS: ${{ vars.KMS_KEY_ALIAS }}
  MAZE_GITHUB_ACTIONS_ROLE_ARN: ${{ secrets.MAZE_GITHUB_ACTIONS_ROLE_ARN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MAZE_GITHUB_OWNER: ${{ vars.MAZE_GITHUB_OWNER }}
  TOFU_VERSION: "1.9.0"

jobs:
  deploy-opentofu:
    name: "Deploy OpenTofu Configuration"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.MAZE_GITHUB_ACTIONS_ROLE_ARN }}
          role-session-name: MazeGitHubActionsSession
          aws-region: ${{ env.AWS_REGION }}

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ env.TOFU_VERSION }}

      - name: Initialize OpenTofu with Backend
        working-directory: infrastructure
        run: |
          tofu init \
            -backend-config="bucket=${S3_BUCKET_NAME}" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="kms_key_id=${KMS_KEY_ALIAS}" \
            -backend-config="dynamodb_table=${DYNAMODB_TABLE_NAME}"

      - name: Plan OpenTofu Changes
        working-directory: infrastructure
        run: tofu plan -var="github_owner=${GITHUB_OWNER}" -var="github_token=${GITHUB_TOKEN}" -out=tfplan

      - name: Apply OpenTofu Changes (Only on Main)
        working-directory: infrastructure
        if: github.ref == 'refs/heads/main'
        run: tofu apply -auto-approve -var="github_owner=${GITHUB_OWNER}" -var="github_token=${GITHUB_TOKEN}" tfplan

      - name: Generate OpenTofu Plan Output
        working-directory: infrastructure
        if: github.event_name == 'pull_request'
        run: |
          echo '```json' > plan_output.md
          jq '.' plan.json >> plan_output.md
          echo '```' >> plan_output.md

      - name: Post Plan Output as PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: infrastructure/plan_output.md
        if: github.event_name == 'pull_request'
