name: Enforce Reviewers on Main Branch

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    branches:
      - main

jobs:
  request-production-approval:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Mark environment approval
        run: echo "This PR to main requires Production approval"
